-- setup-saved-properties.sql
-- Run this in your Supabase SQL Editor to set up the saved_properties table

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.saved_properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  property_id TEXT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Add Unique Constraint safely
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'saved_properties_user_id_property_id_key'
  ) THEN
    ALTER TABLE public.saved_properties 
      ADD CONSTRAINT saved_properties_user_id_property_id_key UNIQUE (user_id, property_id);
  END IF;
END $$;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.saved_properties ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies (Drop first to avoid conflicts if re-running)
DROP POLICY IF EXISTS "Users can view own saved properties" ON public.saved_properties;
CREATE POLICY "Users can view own saved properties"
  ON public.saved_properties
  FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own saved properties" ON public.saved_properties;
CREATE POLICY "Users can insert own saved properties"
  ON public.saved_properties
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own saved properties" ON public.saved_properties;
CREATE POLICY "Users can delete own saved properties"
  ON public.saved_properties
  FOR DELETE
  USING (auth.uid() = user_id);
